# Generated by Django 3.2.6 on 2021-08-15 16:03

from django.db import migrations
from django.contrib.auth.hashers import make_password


def default_site_config(apps, schema_editor):
    """Default site configurations"""

    User = apps.get_model("core", "User")
    User.objects.create(
        username="admin",
        first_name="Admin",
        last_name="Admin",
        password=make_password("cbt_admin"),
        is_staff=True,
        is_superuser=True,
    )

    Subject = apps.get_model("core", "Subject")
    Subject.objects.bulk_create(
        [
            Subject(name="Mathematics"),
            Subject(name="English"),
        ]
    )

    StudentClass = apps.get_model("core", "StudentClass")
    StudentClass.objects.bulk_create(
        [
            StudentClass(name="JSS 1"),
            StudentClass(name="JSS 2"),
        ]
    )

    AcademicTerm = apps.get_model("core", "AcademicTerm")
    AcademicTerm.objects.bulk_create(
        [
            AcademicTerm(name="Term 1"),
            AcademicTerm(name="Term 2"),
        ]
    )

    AcademicSession = apps.get_model("core", "AcademicSession")
    AcademicSession.objects.bulk_create(
        [
            AcademicSession(name="2024/2025"),
        ]
    )


def reverse_default(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.delete()
    Subject = apps.get_model("core", "Subject")
    Subject.objects.delete()
    StudentClass = apps.get_model("core", "StudentClass")
    StudentClass.objects.delete()
    AcademicTerm = apps.get_model("core", "AcademicTerm")
    AcademicTerm.objects.delete()
    AcademicSession = apps.get_model("core", "AcademicSession")
    AcademicSession.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_site_config, reverse_default),
    ]
