# Generated by Django 4.1.2 on 2022-11-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_academicsession_academicterm_alter_user_options_and_more"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="author",
        ),
        migrations.AlterModelOptions(
            name="exam",
            options={"ordering": ["-published", "-created"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="question",
            name="exam",
        ),
        migrations.AddField(
            model_name="exam",
            name="choices_per_question",
            field=models.IntegerField(
                default=4, help_text="Number of choices per question."
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(blank=True, to="exam.question"),
        ),
        migrations.AddField(
            model_name="question",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subject",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
