# Generated by Django 4.1.2 on 2022-11-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_academicsession_academicterm_alter_user_options_and_more"),
        ("exam", "0002_remove_submission_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="class_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.studentclass",
            ),
            preserve_default=False,
        ),
    ]
